name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # ✅ REQUIRED for GHCR
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Log in to GHCR
      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u imgnxorg --password-stdin

      # ✅ Build and tag the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/imgnxorg/my-next-app:latest .

      # ✅ Push Docker image to GHCR
      - name: Push Docker image
        run: |
          docker push ghcr.io/imgnxorg/my-next-app:latest

      # ✅ Auto-Link Package to Repo
      - name: Auto-Link Package to Repo
        env:
          GH_TOKEN: ${{ secrets.GHCR_PAT }} # ✅ Use GHCR_PAT instead of GITHUB_TOKEN
        run: |
          gh api -X PATCH "https://api.github.com/orgs/imgnxorg/packages/container/my-next-app" \
          -f repository="imgnxorg/my-next-app"
